<?
function msd2014_block_info() {
	$blocks['footer_left_column'] = array(
		'info' => t('Footer Left Column'),
	);
	$blocks['footer_center_column'] = array(
		'info' => t('Footer Center Column'),
	);
	$blocks['footer_right_column'] = array(
		'info' => t('Footer Right Column'),
	);
	return $blocks;
}

function msd2014_block_configure($delta = '') {
	
	$form = array();
	
	if ($delta == 'footer_left_column') {
		$form['body'] = array(
	        '#type' => 'text_format',
	        '#title' => t('Block body'),
			'#required' => TRUE,
	        '#default_value' => variable_get('msd2014_footer_left_column', ""),
		);
	} else if ($delta == 'footer_center_column') {
		$form['body'] = array(
	        '#type' => 'text_format',
	        '#title' => t('Block body'),
			'#required' => TRUE,
	        '#default_value' => variable_get('msd2014_footer_center_column', ""),
		);
	} else if ($delta == 'footer_right_column') {
		$form['body'] = array(
	        '#type' => 'text_format',
	        '#title' => t('Block body'),
			'#required' => TRUE,
	        '#default_value' => variable_get('msd2014_footer_right_column', ""),
		);
	}
	
	return $form;
	
}

function msd2014_block_view($delta = '') {
	$block = array();
	if($delta == "footer_left_column") {
		$block['content'] = variable_get('msd2014_footer_left_column', "");
	} else if($delta == "footer_center_column") {
		$block['content'] = variable_get('msd2014_footer_center_column', "");
	} else if($delta == "footer_right_column") {
		$block['content'] = variable_get('msd2014_footer_right_column', "");
	}
	return $block;
}

function msd2014_preprocess_block(&$variables) {
	if($variables['block']->delta == 'footer_left_column') {
		$variables['classes_array'][] = "footer_left_column";
	}
	if($variables['block']->delta == 'footer_center_column') {
		$variables['classes_array'][] = "footer_center_column";
	}
	if($variables['block']->delta == 'footer_right_column') {
		$variables['classes_array'][] = "footer_right_column";
	}
}

function msd2014_block_save($delta = '',$edit = array()) {
	if ($delta == 'footer_left_column') {
		variable_set('msd2014_footer_left_column', $edit['body']["value"]);
	} else if ($delta == 'footer_center_column') {
		variable_set('msd2014_footer_center_column', $edit['body']["value"]);
	} else if ($delta == 'footer_right_column') {
		variable_set('msd2014_footer_right_column', $edit['body']["value"]);
	}
}
