<?php
function redirectmsd_menu() {
	
	$items['redirect'] = array(
		'title' => 'Example Page',
		'page callback' => 'redirectmsd_page',
		'access arguments' => array('access content'),
		'file' => 'redirectmsd.page.inc',
		'type' => MENU_SUGGESTED_ITEM,
	);

	$items['admin/redirectmsd'] = array(
		'title' => 'Redirect MSD',
		'description' => 'Manage Webform / Lightbox redirections',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('redirectmsd_admin_form'),
		'access callback' => 'user_access',
		'access arguments' => array('administer site configuration'),
		'file' => 'redirectmsd.admin.inc',
		'type' => MENU_NORMAL_ITEM,
	);
		  
	$items['admin/redirectmsd/delete'] = array(
		'title' => t('Delete Lightbox Redirect'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('redirectmsd_delete', 2),
		'access arguments' => array('administer site configuration'),
		'file' => 'redirectmsd.admin.inc',
		'type' => MENU_NORMAL_ITEM,
	);
		  
	$items['admin/redirectmsd/create'] = array(
		'title' => t('Create Lightbox Redirect'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('redirectmsd_create', 2),
		'access arguments' => array('administer site configuration'),
		'file' => 'redirectmsd.admin.inc',
		'type' => MENU_NORMAL_ITEM,
	);

	return $items;
	
}
