<?php
function redirectmsd_menu() {
	
	$items['redirect/%'] = array(
		'title' => 'Redirect',
		'page callback' => 'redirectmsd_page',
		'page arguments' => array(1),
		'access arguments' => array('access content'),
		'file' => 'redirectmsd.page.inc',
		'type' => MENU_SUGGESTED_ITEM,
	);

	$items['admin/redirectmsd'] = array(
		'title' => 'Redirect MSD',
		'description' => 'Manage Webform / Lightbox redirections',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('redirectmsd_admin_form'),
		'access callback' => 'user_access',
		'access arguments' => array('administer redirectmsd'),
		'file' => 'redirectmsd.admin.inc',
		'type' => MENU_NORMAL_ITEM,
	);
		  
	$items['admin/redirectmsd/delete/%'] = array(
		'title' => t('Delete Lightbox Redirect'),
		'page callback' => 'redirectmsd_delete',
		'page arguments' => array(3),
		'access arguments' => array('administer redirectmsd'),
		'file' => 'redirectmsd.admin.inc',
		'type' => MENU_NORMAL_ITEM,
	);
	
	$items['admin/redirectmsd/add'] = array(
		'title' => t('Create Lightbox Redirect'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('redirectmsd_edit'),
		'access arguments' => array('administer redirectmsd'),
		'file' => 'redirectmsd.admin.inc',
		'type' => MENU_NORMAL_ITEM,
	);
	
	$items['admin/redirectmsd/edit/%'] = array(
		'title' => t('Create Lightbox Redirect'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('redirectmsd_edit', 3),
		'access arguments' => array('administer redirectmsd'),
		'file' => 'redirectmsd.admin.inc',
		'type' => MENU_NORMAL_ITEM,
	);
	
	return $items;
	
}

/**
 * Implements hook_permission().
 */
function redirectmsd_permission() {
	return array(
	'administer redirectmsd' => array(
		'title' => t('Administer MSD Lightbox Redirects'),
		'description' => t('Allow the user to administer MSD Lightbox Redirects'),
 	),
	);
}